services:
  nginx-1:
    image: nginx:latest
    container_name: nginx-1
    ports:
      - "8090:80"

  nginx-2:
    image: nginx:latest
    container_name: nginx-2
    ports:
      - protocol: tcp
        target: 80
        published: "8091"