apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-label
  labels:
    team: backend
    env: development
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80